# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 12
script:
  - pwd
  - ls -l ~
  - echo "REACT_APP_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" > ~/.env
  - echo "REACT_APP_AMAP_API_KEY=$AMAP_API_KEY" > ~/.env
  - npm test
  - npm run build

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN # Set in the settings page of your repository, as a secure variable
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
