# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 12
script:
  - npm test
  - npm run build

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: build
  on:
    branch: master
